{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Values.global.namespace | default "brewflow" }}
  labels:
    app: {{ include "common.name" . }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "common.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP

          env:
            {{- include "common.env" . | nindent 12 }}
            {{- include "local.env" . | nindent 12 }}

          resources:
            {{- if .Values.resources }}
              {{- toYaml .Values.resources | nindent 12 }}
              {{- else }}
              {{- toYaml .Values.global.resources | nindent 12 }}
              {{- end }}

          {{- include "common.probes" . | nindent 10 }}
  {{- end }}
