{{- define "common.headless-service" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-headless
  namespace: {{ .Values.global.namespace | default "brewflow" }}
  labels:
    app: {{ include "common.name" . }}
spec:
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "common.name" . }}
{{- end }}
