{{- if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: loki
data:
  config.yaml: |
{{ .Files.Get "observability/loki/loki-config.yml" | indent 4 }}
{{- end }}
