{{- if .Values.mailhog.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog
  namespace: brewflow-infra
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: "{{ .Values.mailhog.image.repository }}:{{ .Values.mailhog.image.tag }}"
          imagePullPolicy: {{ .Values.mailhog.image.pullPolicy }}
          ports:
            - name: smtp
              containerPort: {{ .Values.mailhog.ports.smtp }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.mailhog.ports.http }}
              protocol: TCP
          resources:
            {{- toYaml .Values.mailhog.resources | nindent 12 }}
{{- end }}
