apiVersion: v2
name: notification-service
description: A Helm chart for notification-service
type: application

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
