apiVersion: v2
name: api-gateway
description: A Helm chart for api-gateway
type: application

version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: common
    version: "1.0.0"
    repository: "file://../common"
